- name: configure common baseline
  hosts: all
  gather_facts: true
  roles:
    - common

- name: configure zabbix server
  hosts: zabbix
  roles:
    - zabbix_server

- name: configure flask app & agent
  hosts: app
  roles:
    - app

- name: configure grafana dashboards
  hosts: grafana
  roles:
    - grafana
