- name: Configuration de la gateway main-gw (sans NAT)
  hosts: main-gw
  become: true
  gather_facts: true
  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: true

    - name: Mise à niveau complète
      apt:
        upgrade: dist

- name: Mise à jour de la machine main-k8s
  hosts: main-k8s
  become: true
  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: true

    - name: Mise à niveau complète
      apt:
        upgrade: dist

# Configuration réseau supprimée - main-k8s a maintenant sa propre IP publique

- name: Mise à jour de la machine main-obs
  hosts: main-obs
  become: true
  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: true

    - name: Mise à niveau complète
      apt:
        upgrade: dist

# Configuration réseau supprimée - main-obs a maintenant sa propre IP publique

- name: Mise à jour de la machine main-app
  hosts: main-app
  become: true
  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: true

    - name: Mise à niveau complète
      apt:
        upgrade: dist

# Configuration réseau supprimée - main-app a maintenant sa propre IP publique
