global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - first_rules.yml
  # - second_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['10.42.0.3:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.42.0.3:9100', '10.42.0.4:9100', '10.42.0.2:9100']
